# Makefile for QSOS Tutorial

DOC=qsos-tutorial

VERSION=2.0

LANG=en

LANGUAGE=english

TITLE=QSOS Tutorial

#List of edocs to be included in Gitit export
PAGES=qsos-tutorial-intro_$(LANG).md qsos-tutorial-templates_$(LANG).md qsos-tutorial-evaluations_$(LANG).md qsos-tutorial-comparisons_$(LANG).md

#List of edocs to be included in other exports
CHAPTERS=qsos-tutorial-head_$(LANG).md $(PAGES) qsos-tutorial-drakkr_$(LANG).md

DOCNAME=$(DOC)-$(VERSION)_$(LANG)

include ../../Makefile.global
