# Makefile for QSOS documentation

DOC=qsos

VERSION=2.0

LANG=fr

LANGUAGE=french

TITLE=Méthode de Qualification et Sélection de logiciels Open Source (QSOS)

#List of edocs to be included in Gitit export
PAGES=qsos-intro_$(LANG).md qsos-process_$(LANG).md qsos-step1_$(LANG).md qsos-step2_$(LANG).md qsos-step3_$(LANG).md qsos-step4_$(LANG).md qsos-community_$(LANG).md qsos-appendixA_$(LANG).md

#List of edocs to be included in other exports
CHAPTERS=qsos-head_$(LANG).md qsos-manifesto_$(LANG).md qsos-changelog_$(LANG).md  $(PAGES) qsos-appendixB_$(LANG).md

DOCNAME=$(DOC)-$(VERSION)_$(LANG)

TEMPLATE=../Template/qsos-template_$(LANG).latex

include ../../Makefile.global
