# Makefile for QSOS Tutorial

DOC=qsos-installation

VERSION=1.0

LANG=fr

LANGUAGE=french

TITLE=Installation QSOS

#List of edocs to be included in Gitit export
PAGES=qsos-o3s-install_$(LANG).md

#List of edocs to be included in other exports
CHAPTERS=qsos-o3s-install-head_$(LANG).md $(PAGES) qsos-o3s-install-drakkr_$(LANG).md

DOCNAME=$(DOC)-$(VERSION)_$(LANG)

TEMPLATE=../Template/qsos-template_$(LANG).latex

include ../../Makefile.global
