# Makefile for QSOS Tutorial

DOC=qsos-install

VERSION=2.0

LANG=en

LANGUAGE=english

TITLE=QSOS Installation

#List of edocs to be included in Gitit export
PAGES=qsos-o3s-install_$(LANG).md qsos-xuleditor-install_$(LANG).md

#List of edocs to be included in other exports
CHAPTERS=qsos-o3s-install-head_$(LANG).md $(PAGES) qsos-o3s-install-drakkr_$(LANG).md

DOCNAME=$(DOC)-$(VERSION)_$(LANG)

TEMPLATE=../Template/qsos-template_$(LANG).latex

include ../../Makefile.global
