# Makefile for QSOS Maintainer Guide

DOC=qsos-maintainer-guide

VERSION=2.0

LANG=en

LANGUAGE=english

TITLE=QSOS Maintainer Guide

#List of edocs to be included in Gitit export
PAGES=qsos-maintainer-intro_$(LANG).md qsos-maintainer-edoc_$(LANG).md qsos-maintainer-tools_$(LANG).md qsos-maintainer-impacts_$(LANG).md qsos-maintainer-web_$(LANG).md qsos-maintainer-i18n_$(LANG).md

#List of edocs to be included in other exports
CHAPTERS=qsos-maintainer-head_$(LANG).md qsos-maintainer-changelog_$(LANG).md $(PAGES) qsos-maintainer-drakkr_$(LANG).md

DOCNAME=$(DOC)-$(VERSION)_$(LANG)

include ../../Makefile.global
